title: Prayer Tree
description: Prayer Tree is a prayer managing tool
github:
  repository_url: https://github.com/eric11eca/PrayerTree
  zip_url: https://github.com/eric11eca/PrayerTree/prayer-tree-windows-installer.zip
show_downloads: true
google_analytics:
